/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2CM.h"
#include "I2CM_I2C.h"
#include "I2CM_PINS.h"
#include "I2CM_I2C_PVT.h"
#include "I2CM_PVT.h"
#include "I2CM_BOOT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "CTRL.h"
#include "CTRL_aliases.h"
#include "ADC.h"
#include "ADC_PIN.h"
#include "ADC_PIN_aliases.h"
#include "S3.h"
#include "S3_aliases.h"
#include "S2.h"
#include "S2_aliases.h"
#include "S1.h"
#include "S1_aliases.h"
#include "S0.h"
#include "S0_aliases.h"
#include "I2CM_SCBCLK.h"
#include "I2CM_sda.h"
#include "I2CM_sda_aliases.h"
#include "I2CM_scl.h"
#include "I2CM_scl_aliases.h"
#include "I2CM_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

